//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StatsGUI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Date To.
        /// </summary>
        public static string ad {
            get {
                return ResourceManager.GetString("ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Director Approved.
        /// </summary>
        public static string ADir {
            get {
                return ResourceManager.GetString("ADir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Due Date for Revolving.
        /// </summary>
        public static string Adv {
            get {
                return ResourceManager.GetString("Adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add AKA to Account.
        /// </summary>
        public static string aka {
            get {
                return ResourceManager.GetString("aka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following items you created have not been approved by a supervisor.
        /// </summary>
        public static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Manager Approved.
        /// </summary>
        public static string AMan {
            get {
                return ResourceManager.GetString("AMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Name.
        /// </summary>
        public static string an {
            get {
                return ResourceManager.GetString("an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to Sub-Account .
        /// </summary>
        public static string asa {
            get {
                return ResourceManager.GetString("asa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asst Dir. Approved.
        /// </summary>
        public static string asdapp {
            get {
                return ResourceManager.GetString("asdapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Director.
        /// </summary>
        public static string asistd {
            get {
                return ResourceManager.GetString("asistd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Manager.
        /// </summary>
        public static string asistm {
            get {
                return ResourceManager.GetString("asistm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asst Man. Approved.
        /// </summary>
        public static string asmapp {
            get {
                return ResourceManager.GetString("asmapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced To.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to Account.
        /// </summary>
        public static string AtA {
            get {
                return ResourceManager.GetString("AtA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attorney Fees.
        /// </summary>
        public static string attorney {
            get {
                return ResourceManager.GetString("attorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attachment is required.
        /// </summary>
        public static string attreq {
            get {
                return ResourceManager.GetString("attreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to My Queue.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waive or Set Aside Small Balance.
        /// </summary>
        public static string Bal {
            get {
                return ResourceManager.GetString("Bal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Comment.
        /// </summary>
        public static string cacc {
            get {
                return ResourceManager.GetString("cacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Director Comment.
        /// </summary>
        public static string casd {
            get {
                return ResourceManager.GetString("casd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Manager Comment.
        /// </summary>
        public static string casm {
            get {
                return ResourceManager.GetString("casm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Customer Information.
        /// </summary>
        public static string Cci {
            get {
                return ResourceManager.GetString("Cci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director Comment.
        /// </summary>
        public static string cd {
            get {
                return ResourceManager.GetString("cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Due Date.
        /// </summary>
        public static string cdd {
            get {
                return ResourceManager.GetString("cdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Comment.
        /// </summary>
        public static string cm {
            get {
                return ResourceManager.GetString("cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Maker.
        /// </summary>
        public static string comake {
            get {
                return ResourceManager.GetString("comake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court Fees.
        /// </summary>
        public static string court {
            get {
                return ResourceManager.GetString("court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Payment Short (less than $6).
        /// </summary>
        public static string cps {
            get {
                return ResourceManager.GetString("cps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string createdby {
            get {
                return ResourceManager.GetString("createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string createdon {
            get {
                return ResourceManager.GetString("createdon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Comment.
        /// </summary>
        public static string cs {
            get {
                return ResourceManager.GetString("cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string cust {
            get {
                return ResourceManager.GetString("cust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date Change.
        /// </summary>
        public static string Ddc {
            get {
                return ResourceManager.GetString("Ddc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date can not pass the 25th.
        /// </summary>
        public static string ddcp {
            get {
                return ResourceManager.GetString("ddcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Deferment.
        /// </summary>
        public static string Def {
            get {
                return ResourceManager.GetString("Def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop your files here.
        /// </summary>
        public static string dfh {
            get {
                return ResourceManager.GetString("dfh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 9-digit Account number is required.
        /// </summary>
        public static string digit {
            get {
                return ResourceManager.GetString("digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        public static string Dir {
            get {
                return ResourceManager.GetString("Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir. Approved.
        /// </summary>
        public static string dirapp {
            get {
                return ResourceManager.GetString("dirapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition.
        /// </summary>
        public static string disp {
            get {
                return ResourceManager.GetString("disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispostion Date.
        /// </summary>
        public static string dispdate {
            get {
                return ResourceManager.GetString("dispdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Last Paid.
        /// </summary>
        public static string dlp {
            get {
                return ResourceManager.GetString("dlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop Attachment.
        /// </summary>
        public static string dnd {
            get {
                return ResourceManager.GetString("dnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Payment Posted.
        /// </summary>
        public static string dpp {
            get {
                return ResourceManager.GetString("dpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Reason.
        /// </summary>
        public static string ear {
            get {
                return ResourceManager.GetString("ear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new AKA.
        /// </summary>
        public static string enaka {
            get {
                return ResourceManager.GetString("enaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new Name/SSN.
        /// </summary>
        public static string enossn {
            get {
                return ResourceManager.GetString("enossn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a reason.
        /// </summary>
        public static string enr {
            get {
                return ResourceManager.GetString("enr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Customer Name.
        /// </summary>
        public static string entname {
            get {
                return ResourceManager.GetString("entname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Reveresed from account number.
        /// </summary>
        public static string entrevfrom {
            get {
                return ResourceManager.GetString("entrevfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Reveresed to account number.
        /// </summary>
        public static string entrevto {
            get {
                return ResourceManager.GetString("entrevto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter type of Fees.
        /// </summary>
        public static string enttype {
            get {
                return ResourceManager.GetString("enttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next due date can not be more that 15 days from the original due date.
        /// </summary>
        public static string errddc {
            get {
                return ResourceManager.GetString("errddc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Fees.
        /// </summary>
        public static string fees {
            get {
                return ResourceManager.GetString("fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honor Same as Cash.
        /// </summary>
        public static string honor {
            get {
                return ResourceManager.GetString("honor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest/Finance Charges.
        /// </summary>
        public static string interest {
            get {
                return ResourceManager.GetString("interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Charges.
        /// </summary>
        public static string late {
            get {
                return ResourceManager.GetString("late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker.
        /// </summary>
        public static string make {
            get {
                return ResourceManager.GetString("make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Approved.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string manager2 {
            get {
                return ResourceManager.GetString("manager2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man. Approved.
        /// </summary>
        public static string mgrapp {
            get {
                return ResourceManager.GetString("mgrapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing information for Attorney Fees.
        /// </summary>
        public static string missingattorney {
            get {
                return ResourceManager.GetString("missingattorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing information for Late Fees.
        /// </summary>
        public static string missinglate {
            get {
                return ResourceManager.GetString("missinglate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing information for NSF Fees.
        /// </summary>
        public static string missingnsf {
            get {
                return ResourceManager.GetString("missingnsf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing information for Repo Fees.
        /// </summary>
        public static string missingrepo {
            get {
                return ResourceManager.GetString("missingrepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be Maker or Co-Maker.
        /// </summary>
        public static string mocm {
            get {
                return ResourceManager.GetString("mocm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Payments.
        /// </summary>
        public static string mp {
            get {
                return ResourceManager.GetString("mp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing information for Court Fees.
        /// </summary>
        public static string mssingcourt {
            get {
                return ResourceManager.GetString("mssingcourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        public static string mult {
            get {
                return ResourceManager.GetString("mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer must have paid within the current month.
        /// </summary>
        public static string mustpay {
            get {
                return ResourceManager.GetString("mustpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Change/ Name Correction.
        /// </summary>
        public static string nc {
            get {
                return ResourceManager.GetString("nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of due date changes on this account to date.
        /// </summary>
        public static string nddc {
            get {
                return ResourceManager.GetString("nddc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item:.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invoice Added.
        /// </summary>
        public static string nia {
            get {
                return ResourceManager.GetString("nia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Next Due Date.
        /// </summary>
        public static string nndd {
            get {
                return ResourceManager.GetString("nndd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Administrator (Hold Ctrl to select multiple users).
        /// </summary>
        public static string notify {
            get {
                return ResourceManager.GetString("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSF Charges.
        /// </summary>
        public static string nsf {
            get {
                return ResourceManager.GetString("nsf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other bills due around the same time.
        /// </summary>
        public static string obd {
            get {
                return ResourceManager.GetString("obd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document in Adobe.
        /// </summary>
        public static string oda {
            get {
                return ResourceManager.GetString("oda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date can not be in the past.
        /// </summary>
        public static string past {
            get {
                return ResourceManager.GetString("past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date can not be after Advanced Date.
        /// </summary>
        public static string payad {
            get {
                return ResourceManager.GetString("payad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Change To.
        /// </summary>
        public static string pct {
            get {
                return ResourceManager.GetString("pct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string pd {
            get {
                return ResourceManager.GetString("pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Fees.
        /// </summary>
        public static string pf {
            get {
                return ResourceManager.GetString("pf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send PIF Letter.
        /// </summary>
        public static string Pif {
            get {
                return ResourceManager.GetString("Pif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for due date change.
        /// </summary>
        public static string rddc {
            get {
                return ResourceManager.GetString("rddc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolving Deferment.
        /// </summary>
        public static string Rdf {
            get {
                return ResourceManager.GetString("Rdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready For Processing.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reimburse or Credit Paid Fees.
        /// </summary>
        public static string Rem {
            get {
                return ResourceManager.GetString("Rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative Comment.
        /// </summary>
        public static string rep {
            get {
                return ResourceManager.GetString("rep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo Charges.
        /// </summary>
        public static string repo {
            get {
                return ResourceManager.GetString("repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative.
        /// </summary>
        public static string representative {
            get {
                return ResourceManager.GetString("representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Required).
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Payment.
        /// </summary>
        public static string Rev {
            get {
                return ResourceManager.GetString("Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse from Account.
        /// </summary>
        public static string rfa {
            get {
                return ResourceManager.GetString("rfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reapply to Account.
        /// </summary>
        public static string rt {
            get {
                return ResourceManager.GetString("rt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorted Amount.
        /// </summary>
        public static string sa {
            get {
                return ResourceManager.GetString("sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press CTRL+F to search for account by name or number.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search2 {
            get {
                return ResourceManager.GetString("Search2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Chance.
        /// </summary>
        public static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Satisfied.
        /// </summary>
        public static string setsat {
            get {
                return ResourceManager.GetString("setsat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN Change.
        /// </summary>
        public static string ssn {
            get {
                return ResourceManager.GetString("ssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string stat2 {
            get {
                return ResourceManager.GetString("stat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat Items For.
        /// </summary>
        public static string StatItem {
            get {
                return ResourceManager.GetString("StatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement.
        /// </summary>
        public static string Stm {
            get {
                return ResourceManager.GetString("Stm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Account.
        /// </summary>
        public static string subaccount {
            get {
                return ResourceManager.GetString("subaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Item Has Been Submitted.
        /// </summary>
        public static string submitted {
            get {
                return ResourceManager.GetString("submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sup. Approved.
        /// </summary>
        public static string supapp {
            get {
                return ResourceManager.GetString("supapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Approved.
        /// </summary>
        public static string Super {
            get {
                return ResourceManager.GetString("Super", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not TBOM).
        /// </summary>
        public static string tbom {
            get {
                return ResourceManager.GetString("tbom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Fee.
        /// </summary>
        public static string tf {
            get {
                return ResourceManager.GetString("tf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To match pay periods.
        /// </summary>
        public static string tmpp {
            get {
                return ResourceManager.GetString("tmpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemType:.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type2 {
            get {
                return ResourceManager.GetString("Type2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file(s) have been uploaded successfully!.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Amount.
        /// </summary>
        public static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Date.
        /// </summary>
        public static string validdate {
            get {
                return ResourceManager.GetString("validdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Valid Finance Amount.
        /// </summary>
        public static string validfin {
            get {
                return ResourceManager.GetString("validfin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Valid Interest Amount.
        /// </summary>
        public static string validint {
            get {
                return ResourceManager.GetString("validint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Approval.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waive Balance Less than $3.
        /// </summary>
        public static string wb {
            get {
                return ResourceManager.GetString("wb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waive Outstanding Fees.
        /// </summary>
        public static string Wof {
            get {
                return ResourceManager.GetString("Wof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waive Small Credit Less than $1.99.
        /// </summary>
        public static string wsc {
            get {
                return ResourceManager.GetString("wsc", resourceCulture);
            }
        }
    }
}
